### ISSUE TITLE
Profile Browser fails with AttributeError: 'bool' object has no attribute '_root'

### ISSUE THREAD

**Issue by rlippmann** [zhuyifei1999/guppy3#42]
I'm doing:

from guppy import hpy
hpy().pb()

and I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rlippmann/git/homeassistant/core/venv/lib/python3.10/site-packages/guppy/heapy/Prof.py", line 2998, in pb
    pa.new_profile_browser(filename)
  File "/home/rlippmann/git/homeassistant/core/venv/lib/python3.10/site-packages/guppy/heapy/Prof.py", line 1670, in new_profile_browser
    return ProfileBrowser(self, filename)
  File "/home/rlippmann/git/homeassistant/core/venv/lib/python3.10/site-packages/guppy/heapy/Prof.py", line 2418, in __init__
    self.display = Display(self.disptab,
  File "/home/rlippmann/git/homeassistant/core/venv/lib/python3.10/site-packages/guppy/heapy/Prof.py", line 821, in __init__
    self.var_xgrid = BooleanVar(xgrid)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 610, in __init__
    Variable.__init__(self, master, value, name)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'bool' object has no attribute '_root'

I get a window to pop up, but I can't do anything.

Am I doing something wrong?

**Comment by zhuyifei1999** [comment]
Hmm seems only happening on Python 3.10, checking

**Comment by zhuyifei1999** [comment]
Caused by https://github.com/python/cpython/commit/bb70b2afe39ad4334a9f3449cddd28149bd628b6

Reading the code:
https://github.com/zhuyifei1999/guppy3/blob/4cb9fcb5d75327544a6875b6caabfdffb70a7e29/guppy/heapy/Prof.py#L820-L825

I think it's not intended to supply the boolean to the BooleanVar constructor.

**Comment by zhuyifei1999** [comment]
Does that fixes it for you? Though the profile browser was such a rarely used component and I don't think there are tests for this (and idk how to write tests for a GUI), so there might still be things broken in it.

**Comment by rlippmann** [comment]
Yes, that fixed it.

Thanks for looking into this so quickly!

Although I don’t really see much use of the profile browser as compared to the tutorials.
