### ISSUE TITLE
Remote monitor mode not available for python >3.8 ?

### ISSUE THREAD

**Issue by lionel-ovaert** [zhuyifei1999/guppy3#45]
Hi, I'm using python 3.10 in one of my projects and wanted to use the remote monitoring mode from guppy3. However, after adding
`import guppy.heapy.RM` I get an error saying `AttributeError: module 'guppy.heapy.heapyc' has no attribute 'interpreter'`.

After some digging, I found that the interpreter is not available for python version above 3.8 (found [here](https://github.com/zhuyifei1999/guppy3/blob/master/src/heapy/heapyc.c#L166))

Is there any specific reason for this ? In the Readme, it's specified that the package works with python 3.9, 3.10 and 3.11.

Any help here would be appreciated :)

**Comment by zhuyifei1999** [comment]
Hi, this was initially disabled in commit 15fa02d393327f256d152e1390412891a892fdab. If I remember correctly it was related to the GIL being refactored, and in our architecture of starting an interpreter in a new thread, the new thread is unable to send a GIL drop request to the original interpreter, causing some deadlock to happen, as far as I remember.

I was also originally waiting on [PEP 554](https://peps.python.org/pep-0554/) and see how I can potentially make use of it, but it's been delayed and delayed and delayed and delayed. The initial code of that PEP was in https://github.com/python/cpython/issues/76785 which was almost 5 years ago!

The reason subinterpreters are used here aren't just for isolating objects between interpreters, but also to make the stdout/stderr point to the remote connection. Otherwise if you do `sys.stdout.write` it'd write to the program's stderr. However, since Python is going for per-interpreter GILs, it's extremely unsafe to hold an object across interpreters, and since guppy literally allows one to grab a reference to any object in the system, I'm not even sure what to do at this point.
